// 本文件仅包含界面演示数据，不代表真实资料、组织、成员或处理结果。
export const prototypeNotice = '当前为交互原型，知识库、资料、证据与回答均为示例数据。';

const governanceCategories = [
  '法律政策', '法人治理', '募捐与资源', '财务税务', '项目活动',
  '信息公开', '内部运营', '外部监督', '未分类',
];

export const spaces = [
  {
    id: 'org', name: '机构知识库', type: 'ORGANIZATION',
    description: '组织制度、法人治理与日常运营的共同知识。',
    assetCount: 12, categoryCount: 9, owner: '林晓', members: 8,
    updated: '今天 10:32', icon: 'book', color: 'purple',
    categories: governanceCategories, favorite: true, recent: true,
  },
  {
    id: 'cases', name: '项目案例库', type: 'PROJECT',
    description: '沉淀项目方案、执行经验与评估成果。',
    assetCount: 2, categoryCount: 4, owner: '陈一舟', members: 6,
    updated: '今天 09:45', icon: 'layers', color: 'blue', shared: true,
    categories: ['项目方案', '执行记录', '评估报告', '成果案例'],
    favorite: true, recent: true,
  },
  {
    id: 'rural', name: '乡村儿童教育专题库', type: 'TOPIC',
    description: '汇聚乡村教育研究、实践案例与方法工具。',
    assetCount: 2, categoryCount: 4, owner: '周知夏', members: 5,
    updated: '昨天 16:20', icon: 'leaf', color: 'green', shared: true,
    categories: ['政策研究', '项目案例', '评估报告', '方法工具'],
    favorite: false, recent: true,
  },
  {
    id: 'policy', name: '公益行业政策库', type: 'INDUSTRY',
    description: '公益行业法律政策、合规要求与政策解读。',
    assetCount: 2, categoryCount: 3, owner: '许安', members: 12,
    updated: '10月6日', icon: 'building', color: 'amber',
    categories: ['法律法规', '政策解读', '合规指南'],
    favorite: false, recent: false,
  },
  {
    id: 'expert', name: '专家方法论库', type: 'EXPERT',
    description: '可复用的调研、评估与项目管理方法。',
    assetCount: 2, categoryCount: 3, owner: '顾明', members: 4,
    updated: '10月5日', icon: 'book', color: 'rose',
    categories: ['调研方法', '评估工具', '项目管理'],
    favorite: false, recent: false,
  },
  {
    id: 'personal', name: '我的工作笔记', type: 'PERSONAL',
    description: '个人阅读笔记、工作记录与待整理想法。',
    assetCount: 2, categoryCount: 3, owner: '林晓', members: 1,
    updated: '昨天 18:06', icon: 'book', color: 'slate',
    categories: ['阅读笔记', '工作记录', '待整理'],
    favorite: false, recent: false,
  },
];

export const fileStatusLabels = {
  ready: '可检索', processing: '处理中', failed: '需处理',
};

export const aiStatusLabels = {
  completed: '完整整理', partial: '部分整理', running: '整理中',
  not_started: '尚未整理', failed: '整理失败', blocked: '安全阻止',
};

// 页码、引文和核验标签均为示例；核验状态与证据来源类型分别保存。
const educationEvidence = [
  {
    id: 'ev-education-1',
    quote: '项目将在三个乡镇开展儿童课后支持活动，以学校与社区协同参与的方式，提供阅读、陪伴与心理支持。',
    page: 12, sourceType: 'AI生成', verification: '待核验',
    claim: '项目采用学校与社区共同支持的实施方式。',
    matchMethod: '内容分片',
  },
  {
    id: 'ev-education-2',
    quote: '每所参与学校每月组织至少两次阅读活动，并在学期末完成一次儿童参与反馈。',
    page: 18, sourceType: 'AI生成', verification: '已核验',
    claim: '项目设定了活动频次与学期反馈机制。',
    matchMethod: '内容分片', verifiedBy: '林婧（示例）',
  },
  {
    id: 'ev-education-3',
    quote: '项目预算应按活动执行、人员支持、评估与管理等科目分别记录，并保留支出凭证。',
    page: null, sourceType: '历史规则', verification: '位置待核验',
    claim: '项目支出需要分类记录并保留凭证。',
    matchMethod: '历史规则',
    warning: '历史规则未提供可靠页码，请在原文中确认位置。',
  },
];

export const assets = [
  {
    id: 'education-v3', spaceId: 'org', title: '乡村儿童教育项目方案 V3',
    format: 'PDF', summary: '以学校与社区协作为基础，为乡村儿童提供持续的阅读与成长支持。',
    category: '项目活动', owner: '周知夏', updated: '今天 10:32',
    fileStatus: 'ready', aiStatus: 'partial', tags: ['乡村教育', '项目方案'],
    fileSize: '2.8 MB', pages: 36, evidence: educationEvidence,
    detailSummary: '本方案围绕三个乡镇的儿童成长需求，设计阅读、课后陪伴与心理支持活动。实施过程由学校、社区伙伴和志愿者共同参与，并通过活动记录与学期反馈持续评估。AI已整理项目目标与实施机制，预算附件尚未完整覆盖。',
    keyPoints: ['学校与社区协作，形成持续支持机制。', '活动频次与儿童反馈是阶段评估的重要依据。', '预算附件尚未完整整理，使用前请阅读原文。'],
    entities: ['乡村儿童', '参与学校', '社区伙伴', '项目志愿者'],
    insights: ['可参考项目案例库的社区阅读经验，细化家校沟通安排。'],
    coverage: 76, version: 'V3', created: '2026年8月15日',
    versions: [
      { version: 'V3', date: '2026年10月8日', current: true, note: '补充执行与评估安排' },
      { version: 'V2', date: '2026年9月21日', current: false, note: '修订活动实施方案' },
      { version: 'V1', date: '2026年8月15日', current: false, note: '首次上传' },
    ],
  },
  {
    id: 'finance-policy', spaceId: 'org', title: '机构财务管理制度',
    format: 'PDF', summary: '明确预算管理、支出审批、报销与财务档案保存要求。',
    category: '财务税务', owner: '林晓', updated: '今天 09:26',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['财务制度', '内部控制'],
    fileSize: '1.6 MB', pages: 24, version: 'V2',
    evidence: [
      { id: 'ev-finance-1', quote: '各部门应在预算范围内申请支出，按授权层级完成审批后方可支付。', page: 8, sourceType: 'AI生成', verification: '待核验', claim: '支出应在预算范围内按授权层级审批。', matchMethod: '内容分片' },
      { id: 'ev-finance-2', quote: '项目相关财务凭证、合同及审批记录应归入对应项目档案，保证支出可追溯。', page: 16, sourceType: 'AI生成', verification: '待核验', claim: '项目财务资料需要归档并保持可追溯。', matchMethod: '内容分片' },
    ],
    keyPoints: ['支出审批与预算授权对应。', '合同、凭证与审批记录共同构成财务档案。'],
    entities: ['财务负责人', '部门负责人', '项目负责人'],
  },
  {
    id: 'board-rules', spaceId: 'org', title: '理事会议事规则',
    format: 'DOCX', summary: '规定理事会召集、议案提交、表决与会议记录的基本程序。',
    category: '法人治理', owner: '许安', updated: '今天 08:50',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['法人治理', '理事会'],
    fileSize: '486 KB', pages: 12, version: 'V1',
    evidence: [{ id: 'ev-board-1', quote: '会议议案应提前送达全体理事，会议记录应载明议案、讨论意见与表决结果。', page: 5, sourceType: 'AI生成', verification: '待核验', claim: '议案需提前送达，决策过程需留存会议记录。', matchMethod: '内容分片' }],
    keyPoints: ['提前送达议案，保障理事充分准备。', '完整记录讨论与表决过程。'],
    entities: ['理事会', '理事长', '秘书处'],
  },
  {
    id: 'school-research', spaceId: 'org', title: '乡村学校需求调研报告',
    format: 'PPTX', summary: '梳理参与学校的阅读资源、课后陪伴与教师支持需求。',
    category: '项目活动', owner: '陈一舟', updated: '昨天 16:40',
    fileStatus: 'ready', aiStatus: 'running', tags: ['需求调研', '乡村教育'],
    fileSize: '8.4 MB', pages: 28, version: 'V1', evidence: [],
    keyPoints: [], entities: [], stage: '正在提取关键对象',
  },
  {
    id: 'cooperation-agreement', spaceId: 'org', title: '学校合作框架协议',
    format: 'DOCX', summary: '明确学校、机构与社区伙伴的合作职责及资料使用边界。',
    category: '法律政策', owner: '许安', updated: '昨天 15:18',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['合作协议', '合规'],
    fileSize: '328 KB', pages: 9, version: 'V1', evidence: [],
  },
  {
    id: 'fundraising-plan', spaceId: 'org', title: '年度筹款与资源合作计划',
    format: 'XLSX', summary: '汇总年度筹款安排、合作伙伴与资源投入计划。',
    category: '募捐与资源', owner: '沈沐', updated: '昨天 14:06',
    fileStatus: 'ready', aiStatus: 'failed', tags: ['年度计划', '资源合作'],
    fileSize: '752 KB', pages: 5, version: 'V1', evidence: [],
    failureReason: 'AI整理服务响应超时。资料仍可检索，可以稍后重新整理。',
  },
  {
    id: 'annual-disclosure', spaceId: 'org', title: '年度信息公开工作指引',
    format: 'PDF', summary: '说明年度报告、财务信息与项目成果的公开安排。',
    category: '信息公开', owner: '林晓', updated: '10月6日',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['信息公开', '年度报告'],
    fileSize: '920 KB', pages: 16, version: 'V1',
    evidence: [{ id: 'ev-disclosure-1', quote: '机构应按规定公开年度工作情况，并说明主要项目进展与资金使用情况。', page: 6, sourceType: 'AI生成', verification: '待核验', claim: '年度公开内容包括项目进展与资金使用情况。', matchMethod: '内容分片' }],
    keyPoints: ['年度公开内容需与正式项目及财务记录对应。'],
  },
  {
    id: 'volunteer-handbook', spaceId: 'org', title: '志愿者参与与儿童保护手册',
    format: 'PDF', summary: '明确志愿服务行为规范、儿童保护原则与事件报告流程。',
    category: '内部运营', owner: '周知夏', updated: '10月6日',
    fileStatus: 'processing', aiStatus: 'not_started', tags: ['志愿者', '儿童保护'],
    fileSize: '3.1 MB', pages: 22, version: 'V1', evidence: [],
    stage: '正在解析内容',
  },
  {
    id: 'audit-report', spaceId: 'org', title: '年度内部监督与改进记录',
    format: 'PDF', summary: '记录内部监督事项、整改责任与跟进安排。',
    category: '外部监督', owner: '顾明', updated: '10月5日',
    fileStatus: 'ready', aiStatus: 'partial', tags: ['内部监督', '持续改进'],
    fileSize: '1.2 MB', pages: 18, version: 'V1', coverage: 68,
    evidence: [{ id: 'ev-audit-1', quote: '整改事项应明确责任人、完成时限与验证方式，形成持续跟进记录。', page: 9, sourceType: 'AI生成', verification: '待核验', claim: '整改任务需要明确责任、时限与验证方式。', matchMethod: '内容分片' }],
    keyPoints: ['已整理整改跟进要求，附件尚未完整覆盖。'],
  },
  {
    id: 'archive-scans', spaceId: 'org', title: '历史项目资料扫描件',
    format: 'PDF', summary: '历史项目留存材料，扫描质量较低，需要重新处理。',
    category: '未分类', owner: '陈一舟', updated: '10月4日',
    fileStatus: 'failed', aiStatus: 'not_started', tags: ['历史资料'],
    fileSize: '12.6 MB', pages: 42, version: 'V1', evidence: [],
    failureReason: '部分页面无法识别，尚未完成检索索引。可重新处理或上传更清晰的原文件。',
  },
  {
    id: 'staff-interview', spaceId: 'org', title: '项目团队访谈记录',
    format: 'TXT', summary: '团队访谈原始记录，包含个人信息，AI整理已被安全策略阻止。',
    category: '内部运营', owner: '林晓', updated: '10月3日',
    fileStatus: 'ready', aiStatus: 'blocked', tags: ['访谈记录', '受限资料'],
    fileSize: '86 KB', pages: 6, version: 'V1', evidence: [],
    failureReason: '资料包含受限个人信息，当前策略不允许AI整理。请由资料负责人确认使用范围。',
    sensitivity: '受限',
  },
  {
    id: 'monthly-operation', spaceId: 'org', title: '九月机构运营简报',
    format: 'DOCX', summary: '汇总本月项目进展、团队协作与重点事项。',
    category: '内部运营', owner: '沈沐', updated: '10月2日',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['运营简报'],
    fileSize: '540 KB', pages: 8, version: 'V1', evidence: [],
  },
  {
    id: 'reading-case', spaceId: 'cases', title: '社区阅读陪伴项目复盘',
    format: 'PDF', summary: '总结社区阅读活动的组织方法、参与反馈与改进经验。',
    category: '成果案例', owner: '陈一舟', updated: '今天 09:45',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['阅读陪伴', '项目复盘'],
    fileSize: '2.1 MB', pages: 20, version: 'V1',
    evidence: [{ id: 'ev-reading-1', quote: '固定活动时间与稳定的志愿者陪伴，有助于儿童持续参与。', page: 11, sourceType: 'AI生成', verification: '待核验', claim: '稳定的时间和陪伴关系有助于持续参与。', matchMethod: '内容分片' }],
    keyPoints: ['稳定的活动安排提升儿童持续参与。'],
  },
  {
    id: 'case-assessment', spaceId: 'cases', title: '儿童成长支持项目评估报告',
    format: 'PDF', summary: '分析项目参与、儿童反馈与学校协作情况。',
    category: '评估报告', owner: '顾明', updated: '昨天 11:20',
    fileStatus: 'ready', aiStatus: 'partial', tags: ['项目评估'],
    fileSize: '3.4 MB', pages: 32, version: 'V2', coverage: 82, evidence: [],
  },
  {
    id: 'rural-methods', spaceId: 'rural', title: '乡村儿童阅读活动工具包',
    format: 'PDF', summary: '提供活动设计、阅读引导与参与反馈的实用模板。',
    category: '方法工具', owner: '周知夏', updated: '昨天 16:20',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['阅读活动', '工具包'],
    fileSize: '4.2 MB', pages: 30, version: 'V1',
    evidence: [{ id: 'ev-methods-1', quote: '活动设计应考虑儿童的阅读兴趣，提供表达感受与分享经历的机会。', page: 7, sourceType: 'AI生成', verification: '待核验', claim: '阅读活动应结合兴趣并提供表达机会。', matchMethod: '内容分片' }],
  },
  {
    id: 'rural-observation', spaceId: 'rural', title: '乡村学校课后活动观察记录',
    format: 'DOCX', summary: '记录课堂之外的儿童活动参与与支持需求。',
    category: '项目案例', owner: '陈一舟', updated: '10月5日',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['学校观察'],
    fileSize: '620 KB', pages: 14, version: 'V1', evidence: [],
  },
  {
    id: 'charity-guide', spaceId: 'policy', title: '公益组织合规工作清单',
    format: 'PDF', summary: '整理机构治理、资金使用与信息公开的工作检查项。',
    category: '合规指南', owner: '许安', updated: '10月6日',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['合规', '检查清单'],
    fileSize: '880 KB', pages: 15, version: 'V1',
    evidence: [{ id: 'ev-charity-1', quote: '合规检查应以适用规定与真实业务记录为依据，保留检查结果和后续处理记录。', page: 4, sourceType: 'AI生成', verification: '待核验', claim: '合规检查应依据适用规定与业务记录。', matchMethod: '内容分片' }],
  },
  {
    id: 'disclosure-brief', spaceId: 'policy', title: '公益信息公开要求解读',
    format: 'DOCX', summary: '梳理信息公开事项、责任分工与资料准备要求。',
    category: '政策解读', owner: '许安', updated: '10月4日',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['信息公开'],
    fileSize: '430 KB', pages: 10, version: 'V1', evidence: [],
  },
  {
    id: 'evaluation-method', spaceId: 'expert', title: '公益项目评估方法手册',
    format: 'PDF', summary: '介绍评估问题设定、资料采集与结果解读方法。',
    category: '评估工具', owner: '顾明', updated: '10月5日',
    fileStatus: 'ready', aiStatus: 'completed', tags: ['评估方法', '研究工具'],
    fileSize: '2.6 MB', pages: 26, version: 'V1',
    evidence: [{ id: 'ev-evaluation-1', quote: '评估问题应与项目目标对应，区分活动完成情况与实际产生的变化。', page: 6, sourceType: 'AI生成', verification: '待核验', claim: '评估应区分活动完成与实际变化。', matchMethod: '内容分片' }],
  },
  {
    id: 'interview-method', spaceId: 'expert', title: '社区需求访谈提纲',
    format: 'DOCX', summary: '为社区访谈提供问题结构与记录建议。',
    category: '调研方法', owner: '顾明', updated: '10月3日',
    fileStatus: 'ready', aiStatus: 'partial', tags: ['社区调研', '访谈'],
    fileSize: '210 KB', pages: 7, version: 'V1', evidence: [], coverage: 70,
  },
  {
    id: 'personal-reading', spaceId: 'personal', title: '组织治理阅读笔记',
    format: 'MD', summary: '记录理事会治理、团队协作与制度建设的阅读思考。',
    category: '阅读笔记', owner: '林晓', updated: '昨天 18:06',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['阅读笔记'],
    fileSize: '24 KB', pages: 4, version: 'V1', evidence: [],
  },
  {
    id: 'personal-review', spaceId: 'personal', title: '本周项目协作备忘',
    format: 'TXT', summary: '汇总跨团队协作事项与下周待跟进问题。',
    category: '工作记录', owner: '林晓', updated: '10月6日',
    fileStatus: 'ready', aiStatus: 'not_started', tags: ['工作备忘'],
    fileSize: '12 KB', pages: 2, version: 'V1', evidence: [],
  },
];
